name: Push docker images to Dockerhub

on:
  push:
    branches: master
    tags:
      - "v*.*.*"

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push latest OpenTOSCA UI
        if: ${{ steps.vars.outputs.tag == 'master' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: opentosca/ui:latest

      - name: Build and push version of OpenTOSCA UI
        if: ${{ steps.vars.outputs.tag != 'master' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: opentosca/ui:${{ steps.vars.outputs.tag }}
