name: Lint

on:
  push:
    branches:
      - master
      - ustutt
  pull_request:

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    container:
      image: node:14

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies from package-lock.json
        run: npm clean-install

      - name: Run linters
        run: npm run lint

      - name: Check production build
        run: npm run build:prod
